global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dotnet_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]