{
 "title": "ContactManagement API v3",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Interval", "query": "1m,,5m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{app=\"$app\"})"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(registry_http_in_flight_requests)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "query_result(registry_http_in_flight_requests{kubernetes_namespace=\"$namespace\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "description": "returns the number of requests made on each endpoint",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{code=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_requests_received_total{code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST Requests",
   "type": "timeseries",
   "description": "returns the number of requests made on post endpoint",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{method=\"POST\",code=\"200\"}[$Interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST Failed requests",
   "type": "timeseries",
   "description": "returns the number of requests made on post endpoint",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{method=\"POST\",code=~\"4..|5..\"}[$Interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "piechart",
   "description": "total number of successful and failed requests",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{code=\"200\", method=\"POST\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{code!=\"200\", method=\"POST\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Post Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_request_duration_seconds_sum{method=\"POST\"}[$Interval])) by (method, code))",
     "legendFormat": "{{Success Requests}}"
    }
   ]
  },
  {
   "title": "GET Requests",
   "type": "timeseries",
   "description": "returns the number of requests made on GET endpoint",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{method=\"GET\",code=\"200\"}[$Interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Failed requests",
   "type": "timeseries",
   "description": "returns the number of requests made on post endpoint",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{method=\"GET\",code=~\"4..|5..\"}[$Interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{code=\"200\", method=\"GET\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{code!=\"200\", method=\"GET\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_request_duration_seconds_sum{method=\"GET\"}[$Interval])) by (method, code))",
     "legendFormat": "{{Success Requests}}"
    }
   ]
  },
  {
   "title": "DELETE Requests",
   "type": "timeseries",
   "description": "returns the number of requests made on DELETEendpoint",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{method=\"DELETE\",code=\"200\"}[$Interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE Failed requests",
   "type": "timeseries",
   "description": "returns the number of requests made on post endpoint",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{method=\"DELETE\",code=~\"4..|5..\"}[$Interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{code=\"200\", method=\"DELETE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{code!=\"200\", method=\"DELETE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_request_duration_seconds_sum{method=\"DELETE\"}[$Interval])) by (method, code))",
     "legendFormat": "{{Success Requests}}"
    }
   ]
  },
  {
   "title": "PUT Requests",
   "type": "timeseries",
   "description": "returns the number of requests made on PUT endpoint",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{method=\"PUT\",code=\"200\"}[$Interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Failed requests",
   "type": "timeseries",
   "description": "returns the number of requests made on post endpoint",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{method=\"PUT\",code=~\"4..|5..\"}[$Interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{code=\"200\", method=\"PUT\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{code!=\"200\", method=\"PUT\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Put Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_request_duration_seconds_sum{method=\"PUT\"}[$Interval])) by (method, code))",
     "legendFormat": "{{Success Requests}}"
    }
   ]
  },
  { "title": "PostgresSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num)"
    }
   ]
  },
  {
   "title": "Sum time new connections",
   "type": "gauge",
   "description": "Sum of time to create new connections.",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npgsql_db_client_connections_create_time_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections used",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
    }
   ]
  },
  {
   "title": "Connection creation count.",
   "type": "gauge",
   "description": "New connection creation count",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npgsql_db_client_connections_create_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of idle and used connections.",
   "type": "timeseries",
   "description": "Count of idle and used connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "npgsql_db_client_connections_usage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of duration of executed commands",
   "type": "stat",
   "description": "Sum of duration of executed commands",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npgsql_db_client_commands_duration_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of executed commands",
   "type": "stat",
   "description": "Count of executed commands.",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npgsql_db_client_commands_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "npgsql_db_client_commands_bytes_written",
     "legendFormat": "__auto"
    },
    {
     "expr": "npgsql_db_client_commands_bytes_read",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"$app\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "RAM Memory Usage",
   "type": "stat",
   "description": "Process Resident Memory Usage",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPUs number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container state",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes allocated in use",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  }
 ]
}